### PR TITLE
user friendly install

### PR DESCRIPTION
**Pull request by nikolaydubina**
hey, nice tool! good work!

I arrived at very similar design before: http://github.com/nikolaydubina/go-enum-example

I recommend to make easier to install your tool. Either make `/cmd/goenums` or make just whole module a main module, since it is not library anyways.

now:

Screenshot 2024-03-19 at 18 53 50

after:
```bash
go install github.com/zarldev/goenums@latest
```

also, I have featured your project in [go-recipes](https://github.com/nikolaydubina/go-recipes?tab=readme-ov-file#-generate-enums-with-goenums) and added badge :)

image

### CODE REVIEW

**Review by zarldev — APPROVED** [review]
Thanks,

**Review by zarldev — CHANGES_REQUESTED** [review]
I have updated the goenums.go  -  I will add the badge thanks.

**Comment by zarldev** [comment]
Added badge

**Comment by nikolaydubina** [comment]
hi, but the main file is not moved right? so it is still impossible to install via `go install`? recommend changing physical layout to make it possible. that would greatly help adoption.

**Pull request closed without merging**
